table = {
    (0, 0, False): "",
    (0, 0, True): "",
    (0, -1, False): "N",
    (0, -1, True): "N_walk",
    (0, 1, False): "S",
    (0, 1, True): "S_walk",
    (-1, 0, False): "W",
    (-1, 0, True): "W_walk",
    (1, 0, False): "E",
    (1, 0, True): "E_walk",
    (-1, -1, False): "NW",
    (-1, -1, True): "NW_walk",
    (1, -1, False): "NE",
    (1, -1, True): "NE_walk",
    (1, 1, False): "SE",
    (1, 1, True): "SE_walk",
    (-1, 1, False): "SW",
    (-1, 1, True): "SW_walk",
}
